name: pages
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  deploy:
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    uses: esportsplus/workflows/.github/workflows/pages.yml@main