name: build
on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true
      NPM_TOKEN:
        required: true
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm config
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          always-auth: true
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'
      - name: npm i
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci
      - name: build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          BRANCH="build"

          # Cleanup
          rm -rf .github

          if [ -f .gitignore ]; then
            sed -i '/^\(\.\/\|\/\)\?build\/\?$/d' .gitignore
          fi

          npm run build

          # Add README disclaimer
          cat > README.md << EOL
          # AUTO-GENERATED BUILD

          This branch is automatically generated by a GitHub Actions workflow. It contains the latest build artifacts for the project.

          ## Important notes

          - **DO NOT** make manual changes to this branch. They will be overwritten on the next workflow run.
          - This branch is intended for deployment purposes only.
          - For development, please refer to the main branch of the repository.
          EOL

          # Configure git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Create a new branch from the current state
          git checkout --orphan temp

          # Add all files
          git add -A

          # Commit changes
          git commit -m "Deploy build" || echo "No changes to commit"

          # Delete the old deploy branch
          if git ls-remote --exit-code --heads origin ${BRANCH} > /dev/null 2>&1; then
            git push origin --delete ${BRANCH}
          fi

          # Rename the temporary branch to deploy
          git branch -m ${BRANCH}

          # Push
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} ${BRANCH}