name: pages
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
concurrency:
  group: "pages"
  cancel-in-progress: false
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm install
          npm install --cpu=x64 --os=linux --libc=glibc sharp
          npm run build --if-present
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4