name: publish to npm

on:
  release:
    types: [published]
  workflow_call:
    secrets:
      NODE_AUTH_TOKEN:
        required: true
  workflow_dispatch:
  workflow_run:
    workflows: [bump]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: 10
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm i
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
